### ISSUE TITLE
JSON Update

### ISSUE THREAD

**Issue by kakd20061** [marcin-filipiak/DeviceConfigJSON#1]
change select to this:         {
          "type": "select",
          "label": "Sieci WiFi",
          "name": "ssid",
          "set": 1,
          "value": [
            {
              "value": "10",
              "label": "opcja 1"
            },
            {
              "value": "12",
              "label": "opcja 2"
            },
            {
              "value": "12",
              "label": "opcja 3"
            }
          ]
        }

**Comment by marcin-filipiak** [comment]
zmieniono values na value
